source 'https://rubygems.org'

gem 'internet_scrabble_club'
gem 'rake', '~> 10.3'

gem 'data_mapper', '~> 1.2'
gem 'dm-postgres-adapter', '~> 1.2'
gem 'dm-validations', '~> 1.2'

gem 'celluloid-io', '~> 0.15'
gem 'events', '~> 0.9'
